# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

extractSeq <- function(Gseq, Left, Right, Strand) {
    .Call('micropan_extractSeq', PACKAGE = 'micropan', Gseq, Left, Right, Strand)
}

ORF_index <- function(Tags, Sequence) {
    .Call('micropan_ORF_index', PACKAGE = 'micropan', Tags, Sequence)
}

