# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ORF_index <- function(Tags, Sequence, trans_tab) {
    .Call('_micropan_ORF_index', PACKAGE = 'micropan', Tags, Sequence, trans_tab)
}

extractSeq <- function(Gseq, Left, Right, Strand) {
    .Call('_micropan_extractSeq', PACKAGE = 'micropan', Gseq, Left, Right, Strand)
}

